module.exports = {
  apps: [
    {
      name: 'persian-carpet-backend',
      script: 'backend/dist/index.js',
      cwd: '/home/user/SafiraFull',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '500M',
      env: {
        NODE_ENV: 'production',
        PORT: 5000,
        DB_HOST: 'localhost',
        DB_PORT: 5432,
        DB_NAME: 'persian_carpet_db',
        DB_USER: 'postgres',
        DB_PASSWORD: 'postgres',
        JWT_SECRET: 'qsRFZYsVeXCxLYdXX/wqo10Xda1K425QABgW2e1HrwQ=',
        JWT_EXPIRE: '7d',
        NOWPAYMENTS_API_KEY: 'KCARK06-V6442D5-NNC3BMB-HW7Q9YV',
        NOWPAYMENTS_IPN_SECRET: '9e08f41f-61a2-4502-9127-44e498047119',
        NOWPAYMENTS_SANDBOX: 'false',
        SMTP_HOST: 'smtp.gmail.com',
        SMTP_PORT: 587,
        SMTP_USER: 'makhdoumiemad@gmail.com',
        SMTP_PASS: 'tazv kpdo ekpq wcfz',
        FRONTEND_URL: 'http://141.11.1.85:5173',
        BACKEND_URL: 'http://141.11.1.85:5000',
        ADMIN_EMAIL: 'emad.devel@gmail.com',
        ADMIN_PASSWORD: 'emadiemadi',
      },
    },
    {
      name: 'persian-carpet-frontend',
      script: 'npx',
      args: 'serve -s build -l 5173',
      cwd: '/home/user/SafiraFull',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '300M',
    },
  ],
};
